version: "3.7"

services:
  db:
    container_name: wheel_db
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: wheel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: wheel
    volumes:
      - data:/var/lib/mysql
    networks:
      - wheelnet

networks:
  wheelnet:
    driver: bridge

volumes:
  data:
