version: "3.7"

services:
  db:
    container_name: wheel_db
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: wheel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: wheel
      TZ: Pacific/Auckland
    volumes:
      - data:/var/lib/mysql
    networks:
      - wheelnet

  app:
    container_name: wheel_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - wheelnet

networks:
  wheelnet:
    driver: bridge

volumes:
  data: