// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Person struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	TeamID    int64  `json:"team_id"`
}

type Team struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Turn struct {
	ID        int64        `json:"id"`
	PersonID  int64        `json:"person_id"`
	TeamID    int64        `json:"team_id"`
	Date      time.Time    `json:"date"`
	CreatedAt sql.NullTime `json:"created_at"`
}
